package gui;

import data.Appointment;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
 * Displays a Dialog for creating Appointments
 * @author Laura Pein
 * 
 */
public class AppointmentDlg extends javax.swing.JDialog {

    public static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("dd.MM.yyyy");
    public static final DateTimeFormatter TIME_FORMATTER = DateTimeFormatter.ofPattern("kk:mm");
    private Appointment app;
    private LocalDate date;
    private boolean isOk;

    /**
     * Creates new form AppointmentDlg
     * @param parent
     * @param modal
     * @param welcomeDate Is used for displaying the selected date
     */
    public AppointmentDlg(java.awt.Frame parent, boolean modal, String welcomeDate) {
        super(parent, modal);
        initComponents();
        this.isOk = true;
        this.date = LocalDate.parse(welcomeDate, DATE_FORMATTER);
        this.welcomeLabel.setText(
                "<html><body>"
                + "Add an Appointment"
                + "on " + welcomeDate
                + "</body></html>");
        this.lbSaveDB.setText(
                "<html><body>"
                + "Also save  <break>"
                + "App. to DB?"
                + "</body></html>");
        this.setSize(490, 250);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfLocation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTime = new javax.swing.JTextField();
        lbSaveDB = new javax.swing.JLabel();
        cbDB = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Appointment");
        getContentPane().setLayout(new java.awt.BorderLayout());

        welcomeLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(welcomeLabel, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Name: ");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);

        tfName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tfName.setText("test");
        tfName.setToolTipText("");
        jPanel1.add(tfName);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Location: ");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2);

        tfLocation.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tfLocation.setText("testest");
        tfLocation.setToolTipText("");
        jPanel1.add(tfLocation);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Starting Time (hh:mm): ");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);

        tfTime.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tfTime.setText("11:11");
        tfTime.setToolTipText("");
        jPanel1.add(tfTime);

        lbSaveDB.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(lbSaveDB);

        cbDB.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(cbDB);

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Done");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDone(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("Discard");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDiscard(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onDone(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDone
        //Wenn true wird der Eintrag später automatisch in die DB geladen.
        boolean loadInDb = false;
        if (this.cbDB.isSelected()) {
            loadInDb = true;
        }
        this.app = new Appointment(tfName.getText(), tfLocation.getText(), date, 
                LocalTime.parse(tfTime.getText(), TIME_FORMATTER), loadInDb);
        this.isOk = true;
        this.dispose();
    }//GEN-LAST:event_onDone

    private void onDiscard(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDiscard
        this.isOk = false;
        this.dispose();
    }//GEN-LAST:event_onDiscard

    public Appointment getApp() {
        return app;
    }

    public boolean isOk() {
        return isOk;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AppointmentDlg dialog = new AppointmentDlg(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbDB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbSaveDB;
    private javax.swing.JTextField tfLocation;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfTime;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
