DROP TABLE Appointments IF EXISTS;

INT GENERATED BY DEFAULT AS IDENTITY
    (START WITH 10 INCREMENT BY 10),

CREATE TABLE Appointments
(
appID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY 
            (START WITH 1, INCREMENT BY 1),
appName VARCHAR(255),
appLocation VARCHAR(255),
appDate DATE,
appTime TIME,
PRIMARY KEY(appID)
);

INSERT INTO Appointments(appName, appLocation, appDate, appTime)
       VALUES
        ('POS', 'Kaindorf', '23.05.2019', '14:55');


